dist: xenial
sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pip
  - $HOME/download

addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy

matrix:
  include:
    - env: PYTHON_VERSION="3.6" NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="0.23.0"
           SKLEARN_VERSION="0.22" STATSMODELS_VERSION="0.9.0" IMBLEARN_VERSION="0.6.0" RICH_VERSION="5.0.0"
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="0.23.0"
           SKLEARN_VERSION="*" STATSMODELS_VERSION="0.9.0" IMBLEARN_VERSION="0.6.2" RICH_VERSION="5.0.0"
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="0.23.0"
           SKLEARN_VERSION="nightly" STATSMODELS_VERSION="0.9.0" IMBLEARN_VERSION="*" RICH_VERSION="5.0.0"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv
  - |
      if [ $SKLEARN_VERSION = "nightly" ]; then
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION cython nose pytest pytest-cov
          # install nightly wheels
          pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
          conda install --yes -c anaconda statsmodels=$STATSMODELS_VERSION
          conda install --yes -c conda-forge imbalanced-learn=$IMBLEARN_VERSION
      else
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION cython nose pytest pytest-cov
          conda install --yes -c anaconda statsmodels=$STATSMODELS_VERSION
          conda install --yes -c conda-forge imbalanced-learn=$IMBLEARN_VERSION
      fi
  - pip install codecov pandas==$PANDAS_VERSION rich==$RICH_VERSION
  - pip install codecov
  - pip install .

script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=rlearn --pyargs rlearn

after_success:
  - codecov