package:
  name: research-learn
  version: "0.1.8"

source:
  url: "https://files.pythonhosted.org/packages/f9/cd/6ea4d0e09cf3d80ce1357acc524ca344d7fd94a69d2640b6dc38ce17c8d7/research-learn-0.1.8.tar.gz"
  sha256: "0f5e1d3baf3bde4a9d431c1f19a276b8f2a3bddc9f4211683709bdbf36450e32"

build:
  number: 0
  noarch: python

requirements:
  host:
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

  run:
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - rlearn

about:
  home: "https://github.com/AlgoWit/research-learn"
  license: "MIT"
  license_file: ""
