package:
  name: research-learn
  version: "0.1.0"

source:
  url: "https://files.pythonhosted.org/packages/5a/e4/320a46a623bc204973b5692714d2723e6eef15c7d1406e560a2685d9febd/research-learn-0.1.0.tar.gz"
  sha256: "2aa0755d4e139df48f5a1670a661405c25754944f4d1ecea6f127ac12810d2de"

build:
  number: 0
  noarch: python

requirements:
  host:
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

  run:
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - rlearn

about:
  home: "https://github.com/AlgoWit/research-learn"
  license: "MIT"
  license_file: ""
