package:
  name: research-learn
  version: "0.1.7"

source:
  url: "https://files.pythonhosted.org/packages/ae/55/f92597014293bc0d3305028cd4682bfa2c98e1a70232a602ef0910edc3f8/research-learn-0.1.7.tar.gz"
  sha256: "0fc5dd12fabde80f4854aa006b13c529bd7e1a8e262dc8d5e41d810340cb3114"

build:
  number: 0
  noarch: python

requirements:
  host:
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

  run:
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - rlearn

about:
  home: "https://github.com/AlgoWit/research-learn"
  license: "MIT"
  license_file: ""
