package:
  name: research-learn
  version: "0.1.3"

source:
  url: "https://files.pythonhosted.org/packages/1c/ee/d96792b5cc600f056572559fe5f6411928824284d5e95574e9aa0e23469c/research-learn-0.1.3.tar.gz"
  sha256: "8b7d7b7b193bccd7cdca36661566f64eaf13aec8ac7c52e1f039d7e59c56712c"

build:
  number: 0
  noarch: python

requirements:
  host:
    - numpy >=1.1
    - pip
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

  run:
    - numpy >=1.1
    - python
    - scikit-learn >=0.21
    - scipy >=0.17
    - pandas >=0.23.0
    - matplotlib >=3.0
    - tqdm >=4.30.0

test:
  requires:
    - coverage
    - pytest
    - pytest-cov
  imports:
    - rlearn

about:
  home: "https://github.com/AlgoWit/research-learn"
  license: "MIT"
  license_file: ""
